### ISSUE TITLE
Frontend: ロール閲覧ページ

### ISSUE THREAD

**Issue by yu23ki14** [hackdays-io/toban#10]
ロールの情報を閲覧するページ
**個人のロールページとは違うので注意**

**Add Core Contributorのボタンは必須**

- [ ] ロールの基本情報（画像、名前、説明、ワークスコープと責任）
- [ ] Contributor一覧（ロールを持っている人たちのリスト。HatのWearerがCoreタグありで、FractionalTokenを持っているひとはCoreタグなし）
- [ ] Core Contributor追加のボタン

![image](https://github.com/user-attachments/assets/0b074a9f-fd68-49c4-862a-c3688ef8ed51)

**Comment by nfttakerun** [comment]
frontend/app/RoleList.tsxに作成しました。

**Comment by nfttakerun** [comment]
frontend/app/RoleList.tsxに作成しました。
