### ISSUE TITLE
CLI 最低限必要な機能を洗い出す

### ISSUE THREAD

**Issue by yu23ki14** [hackdays-io/toban#100]
Hackdays内の運用で必要な最低限の機能を整理する。
管理者、ロール保持者、それ以外　の3つのパターンで考えるのがいいかな

**Comment by nfttakerun** [comment]
担当します！

**Comment by nfttakerun** [comment]
## A.管理者(プロジェクトリーダー)

※設定済項目の削除/修正は一旦なしで

- 原資ウォレット接続
    - ウォレット接続
- プロジェクトの作成
    - プロジェクト名の入力
    - ~~プロジェクト概要の入力~~
    - プロジェクト期間の入力（開始日と終了日）
- ロールの作成
    - ロール名の定義
    - ロールの義務の設定（記入）
    - 作成済ロールの一覧表示
- プロジェクトメンバーの召集
    - プロジェクトメンバーの登録
- ロールの付与
    - メンバーにロールを付与
    - 各ロールに紐づいたメンバーを一覧表示
    - 各メンバーに付与されたロールを一覧表示
- 報酬分配イベントの定義
    - イベント名の入力（例：4半期トークン還元）
    - ~~イベント概要の入力~~
- 報酬分配比率の設定
    - 各ロールに報酬分配比率を設定
    - ロール名と報酬分配比率を一覧表示
    - 各メンバーの報酬分配比率を一覧表示（保有ロールにより最終的な比率は異なる）
- 報酬分配の実行（Split Contract）
    - 接続済ウォレットから分配するトークン総額の設定
    - 各メンバーの分配報酬総額を表示（保有ロールにより最終的な分配額は異なる）
    - 報酬分配の実行処理（署名）
    - 報酬分配後のウォレット残額表示

**Comment by nfttakerun** [comment]
## B.ロール保持者(プロジェクトメンバー)

※設定済項目の削除/修正は一旦なしで。←自分の付与済ロールを途中棄権、分配報酬の受取拒否するなど

- 報酬受取ウォレット接続
    - ウォレット接続
- 保有ロールの参照
    - 保有ロール及びそれら従事期間（開始日and/or継続期間）の一覧表示
- お手伝いメンバーへの報酬分配（Fraction Token）
    - お手伝いメンバーのウォレットアドレス指定
    - お手伝いメンバーへ接続済ウォレットから分配するトークン総額を指定
    - 報酬分配の実行処理（署名）※ここ違うかも

**Comment by nfttakerun** [comment]
## C.お手伝いメンバー(準プロジェクトメンバー)

※設定済項目の削除/修正は一旦なしで。←分配報酬の受取拒否するなど

- ?

**Comment by nfttakerun** [comment]
管理者の動き

## プロジェクトの作成
- view: プロジェクトの一覧
    - ProjectA, ProjectBみたいなイメージ
- view: プロジェクトの詳細
    - ProjectA; “3泊4日プログラミング合宿” みたいなイメージ

## ロールの作成
- view: ロールの一覧
    - RoleA, RoleB, RoleCみたいなイメージ
- view: 各ロールの詳細
    - RoleA; “掃除当番” みたいなイメージ

## ロールの付与（個人アドレスと紐付け）
- view: 個人の持っているロール一覧
    - address1; RoleA, RoleB みたいなイメージ
- view: ロールの一覧（定義済ロールに割り当てられた人数確認）
    - RoleA(1), RoleB(2), RoleC(3)みたいなイメージ
- view: ロールの一覧（定義済ロールに割り当てられたアドレス確認）
    - RoleA(address1), RoleB(address1, address2), RoleC(address2, address3)みたいなイメージ

## 分配率の仮計算
- view: 仮計算結果
    - address1 = 10%
    - address2 = 30%
    - address3 = 60%
- view: 個人の分配率内訳詳細
    - address1; RoleA: x% + RoleB: y% + RoleC: z% みたいなイメージ

## Splitの作成 (view: Splitsコントラクトアドレスや分配率など)
- view: Splitsコントラクトアドレス
    - contract address; 0x…みたいなイメージ
- view: 分配率の一覧
    - address1 = 10%
    - address2 = 30%
    - address3 = 60%
- view: 個人の分配率内訳詳細
    - address1; RoleA: x% + RoleB: y% + RoleC: z% みたいなイメージ
- view: Deposit額の表示
    - Deposit; xETHみたいなイメージ
- view: ガス代の仮計算額の表示
    - Gas fee; xETHみたいなイメージ
- view: 分配額の一覧（概算値、ガス代分どうする？？）
    - address1; xETH
    - address2; yETH
    - address3; zETHみたいなイメージ
