### ISSUE TITLE
Frontend: Splitter一覧ページ

### ISSUE THREAD

**Issue by yu23ki14** [hackdays-io/toban#13]
つくられたSplitter一覧のページ

- [ ] Splittersのリスト（名前、メンバー人数、作成日、チェーン、アドレス/ENS）
- [ ] Splitter作成画面へのリンク

プロジェクトごとのSplitterの取得方法
SplitMakerをFactoryから決定論アドレスでデプロイできるようにして、プロジェクトごとに作れば、getRelatedSplitsをつかって取れたりする？
https://docs.splits.org/sdk/data#getrelatedsplits

![image](https://github.com/user-attachments/assets/232c94dc-96a5-48af-89d2-9aadd3eaad66)

**Comment by nfttakerun** [comment]
app/SplitsList.tsxに作成しました。

**Comment by nfttakerun** [comment]
app/SplitsList.tsxに作成しました。
