### ISSUE TITLE
INCORRECT ACCESS CONTROL

### ISSUE THREAD

**Issue by yu23ki14** [hackdays-io/toban#139]
# SSP_26977_134

### Description
<p>Access control plays an important role in segregation of privileges in smart contracts and other applications. If this is misconfigured or not properly validated on sensitive functions, it may lead to loss of funds, tokens and in some cases compromise of the smart contract. <br><br>The contract SplitsCreator is importing an access control library @openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol but the function create is missing the modifier onlyOwner.</p>

### Remediation
<p>It is recommended to go through the contract and observe the functions that are lacking an access control modifier. If they contain sensitive administrative actions, it is advised to add a suitable modifier to the same</p>

### Code Snapshot
https://github.com/hackdays-io/toban/blob/main/pkgs/contract/contracts/splitscreator/SplitsCreator.sol#L36-L141
<hr/>

**Comment by aowheel** [comment]
SolidityScanからissueを立てる実験
