### ISSUE TITLE
BigBangコントラクトをUpgradeableにする

### ISSUE THREAD

**Issue by yu23ki14** [hackdays-io/toban#141]

**Comment by mashharuki** [comment]
https://zenn.dev/razokulover/articles/708bcf4b9623c5
https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable

 ↑ この辺とか参考になりそうですね。

**Comment by mashharuki** [comment]
どのパターンのupgradableにするか決めないとですね。

- デプロイスクリプトの改修。
- upgrade用のスクリプトの追加

が必要ですかね。

**Comment by mashharuki** [comment]
https://github.com/hackdays-io/mint-rally/blob/staging/hardhat/scripts/helper/upgrade.ts
↑ mintrallyの実装

**Comment by mashharuki** [comment]
https://github.com/NomicFoundation/hardhat-ignition/tree/development/examples/upgradeable

↑ upgradeable のサンプルコードがあった。

**Comment by mashharuki** [comment]
https://www.npmjs.com/package/@openzeppelin/hardhat-upgrades

**Comment by mashharuki** [comment]
<img width="1077" alt="スクリーンショット 2024-10-14 21 33 02" src="https://github.com/user-attachments/assets/5ef76f9a-e695-4f42-9084-18f141446e69">
テストコードが通るように修正しました！
