### ISSUE TITLE
ENS: Splitsを作成したときにENSを紐づける

### ISSUE THREAD

**Issue by yu23ki14** [hackdays-io/toban#15]
Splitterの作成時に、Subdomainとしてhackdays.toban.ethをSplitterに紐づける

- [ ] SplitterCreatorのcreate関数TX時にSubdomainを紐づける
- [ ] SplitterリストページでENSを表示

**Comment by mashharuki** [comment]
ENSの紐付けはここが参考になりそう。

https://rainbowkit-demo.vercel.app/

https://codesandbox.io/p/devbox/fervent-thunder-foktft

**Comment by mashharuki** [comment]
```ts
import { useAccount, useEnsAddress, useEnsAvatar, useEnsName } from 'wagmi';
import { normalize } from 'viem/ens';
import { formatAddress } from '@ens-tools/format';

export const NameLookup = () => {
    const name = normalize("luc.eth");
    const { data: avatar } = useEnsAvatar({ name })
    const { data: ethereum } = useEnsAddress({ name, coinType: 60 });

    return (
        <div>
			{ethereum && formatAddress(ethereum)}<br />
			{avatar && <img src={avatar} />}
		</div>
    );
};
```

**Comment by mashharuki** [comment]
りょーまさんに確保してもらったENS情報。

https://ens.app/toban.eth

**Comment by mashharuki** [comment]
https://docs.ens.domains/web/subdomains

**Comment by mashharuki** [comment]
https://docs.ens.domains/wrapper/overview
↑ subドメインってERC1155で発行されるのか！ 知らなかった！！

**Comment by mashharuki** [comment]
https://docs.ens.domains/wrapper/creating-subname-registrar#creating-and-deploying-your-registrar-contract

↑ 見つけた！！ここっぽい！

**Comment by mashharuki** [comment]
スマートコントラクトのサンプルコードは下記にあるそうです！！
https://github.com/ensdomains/ens-contracts/tree/feature/subdomain-registrar/contracts/subdomainregistrar

**Comment by mashharuki** [comment]
NameWrapperコントラクトを用意する必要があるっぽいですね

**Comment by mashharuki** [comment]
以下、サブドメインと NameWrapperに関するドキュメントの日本語訳です。

サブドメイン

名前はさまざまな状況で便利です。私たちは、アドレスが使用される場所ならどこでも名前を使用できるべきだと考えています。あなたが操作するスマートコントラクトには名前があり、お気に入りの取引所の入金アドレスにも名前があり、また、お気に入りのDAOにも名前があります。もしかすると、ウォレットを整理するためにサブネームを使っているかもしれません。

例:

vault
domico
subname
nick
cold
.nick.eth
幸運にも、ENSプロトコルにはさまざまな機能があり、自由に利用することができます。アプリのユーザーにサブドメインを提供したり、自分自身のために設定したりと、さまざまな方法でサブドメインを利用することができます。

特にスマートコントラクトに名前を付けることに興味がある場合は、「Naming Smart Contracts」のページをご覧ください。

既製のツール

NameWrapper
NameWrapperは、信頼性の高いオンチェーンのサブドメインを発行するスマートコントラクトです。NameWrapperのサブドメインはERC1155形式のNFTとして提供され、転送、販売、または取引が可能です。

さらに、NameWrapperのサブネームにはフューズ（fuzes）があり、これにより権限を制限したり、サブネームを完全に解放することができます。ENS Manager Appから直接NameWrapperを操作することができます。

NameWrapperの概要

レガシーサブドメイン
ETHRegistrarの前バージョンでは、名前に対してサブドメインを登録することができました。これらのサブドメインは常に所有者によって管理され、転送が可能です。また、これらはオンチェーンで保存されますが、ERC1155の形式ではありません。

レガシーサブドメインを登録するには、ENS RegistryコントラクトのsetSubnodeRecord関数を呼び出します。

独自のリゾルバを作成する
Solidityで独自のリゾルバを書くことも可能で、これにより名前やサブネームの解決方法に関して完全なプログラム制御を持つことができます。これにはスマートコントラクトのデプロイが必要です。

オフチェーンとレイヤー2
レイヤー2、データベース、ファイルなど、オフチェーンの場所からデータを読み込むために、リゾルバはCCIP Readを利用してオフチェーンの場所からデータを読み込むことができます。

テンプレートリゾルバのデプロイや、オフチェーンからデータを読み込むためのライブラリを簡単に利用できるツールも用意されています。

EVMゲートウェイ
EVMゲートウェイは、EVM互換チェーンから信頼性の高い方法でストレージスロットを読み込むリゾルバを作成するためのSolidityツールのセットです。現在、OptimismとArbitrumをサポートしています。

CCIPツール
メインネットにコントラクトをデプロイする手間を省きたい場合は、ccip.toolsのプロキシファクトリーを利用できます。これにより、低コストでCCIPエンドポイントからデータを読み込むリゾルバを簡単にデプロイすることができます。

この方法を使用すると、Solidityコードを書かずに、自分のゲートウェイAPIからデータを読み込むリゾルバを簡単にデプロイできます。

サブネーム・レジストラの作成

ユースケースのセクションで、他の人がサブネームを自動的に登録または請求できるようにするために、自分自身の「レジストラ」を立ち上げる機能について説明しました。たとえば、ラップされたサブネームを無料で提供したい場合や、有料で提供したい場合があるかもしれません。あるいは、英数字の名前だけを許可するなど、サブネームに特定のルールを適用したい場合もあるでしょう。これらはすべて可能であり、この記事ではそのために必要な手順を詳しく説明します。まずはユースケースのセクションを読んで、決定すべき事項の概要を理解することをお勧めします。

前提条件

このガイドは、親の名前（例: myname.eth）がすでにラップされていることを前提としています。名前がラップされているかどうか確認したい場合は、Managerアプリの「More」タブを見てください。名前がラップされていない場合はその旨が表示され、「Wrap Name」ボタンが表示されます。

もし解放されたサブネーム（Emancipated subnames）やその他のフューズ（fuses）を燃やしたサブネームを発行したい場合、親の名前は最初に「ロック」されている必要があります。これは、ENS Managerアプリの「Permissions」タブで設定できます。

名前をロックする（つまり、ラップを解除する権限を取り消す）ことは、元に戻せない変更です。名前をロックした後は、ラップを解除することができなくなります。これは、すべてのサブネームの保有者に対するセキュリティ保証です。これにより、親の名前の所有者がName Wrapperのセキュリティ保証を回避することができなくなります。

最初はテストネット（Sepolia/Holesky）で開発やテスト目的で行うのが良いでしょう。

レジストラコントラクトの作成とデプロイ

新しいサブネームを作成するには、コントラクトでNameWrapperコントラクトのsetSubnodeOwnerまたはsetSubnodeRecordのいずれかを呼び出す必要があります。また、必要に応じてフューズと有効期限も同時に渡します。

go
コードをコピーする
NameWrapper.setSubnodeOwner(bytes32 parentNode, string label, address owner, uint32 fuses, uint64 expiry)

// 例
setSubnodeOwner(
    0x6cbc..., // 親ノードの名前ハッシュ（例: "myname.eth"）
    "sub", // 作成するサブネームのラベル
    0x1234..., // 新しいサブネームの所有者にしたいアドレス
    65536, // 燃やしたいフューズビットをORで結合
    2021232060 // サブネームの有効期限
)
go
コードをコピーする
NameWrapper.setSubnodeRecord(bytes32 parentNode, string label, address owner, address resolver, uint64 ttl, uint32 fuses, uint64 expiry)

// 例
setSubnodeRecord(
    0x6cbc..., // 親ノードの名前ハッシュ（例: "myname.eth"）
    "sub", // 作成するサブネームのラベル
    0x1234..., // 新しいサブネームの所有者にしたいアドレス
    0x5678..., // 新しいサブネームに設定するリゾルバのアドレス
    0, // 新しいサブネームに設定するTTL
    65536, // 燃やしたいフューズビットをORで結合
    2021232060 // サブネームの有効期限
)
公開する登録関数は通常、親ノード（名前ハッシュ）とサブネームのラベルを入力として受け取ります。

c
コードをコピーする
register(bytes32 parentNode, string calldata label)
その後、内部でコントラクトがsetSubnodeRecordを呼び出し、残りのパラメーターをユーザーに代わって設定します。

owner: 通常、呼び出し元アカウント（msg.sender）
resolver: 通常、デフォルトのパブリックリゾルバ（resolver.eth）
ttl: 0
fuses: 目的に応じて設定します。詳細はユースケースのセクションを参照してください。通常は解放されたレンタルサブネームの場合は65536、解放された「永久」名の場合は327680です。
expiry: 目的に応じて設定します。特定の期間サブネームをレンタルする場合、この有効期限はその期間を反映します。「永久」名の登録を許可する場合は、有効期限を親名の現在の有効期限と同じに設定します。
もちろん、登録者にもっと多くの権限や利便性を提供したい場合、これらのパラメーターのいくつかを公開登録関数に渡せるようにすることもできます。

リゾルバレコードの設定

サブネームレジストラで同じ登録トランザクション内でサブネームにレコードを設定したい場合は、少し異なる手順が必要です。その場合は、以下の手順を実行します。

setSubnodeOwnerを呼び出し、サブネームの一時的な所有者としてコントラクト自身（address(this)）を設定します。この最初のステップは、コントラクトがサブネームのレコードを設定する権限を持つために、デフォルトのパブリックリゾルバに必要です。

必要なリゾルバメソッドを呼び出します。これらは、サブネームに事前に設定したいレコード（例えば、サブネームが指すETHアドレス）である可能性があります。または、登録者に渡すレコードで、サブネームを登録し、一度のトランザクションで任意のレコードを設定できるようにする場合もあります。

setSubnodeRecordを呼び出し、この時点でサブネームの実際の所有者を設定します。この時点で、適切なフューズと有効期限を設定する必要もあります。

料金の徴収

「レンタル」レジストラを設定する場合、登録関数で一定量のETHを送るよう要求する必要があります。

または、ユーザーにERC-20トークンを使用させることも選択できます。そのためには、通常、トークンコントラクトのtransferFromメソッドを呼び出します。これは、登録者がまずそのトークンの支出者としてあなたのコントラクトを承認する必要があることを意味し、特定のトークン数を登録するために無制限の支出を承認するか、特定のトークン数を承認するための別の承認トランザクションを実行する必要があります。

参考実装

幸いなことに、ゼロから始める必要はありません！ENS Labsの開発者が、以下のリンクでいくつかのサンプルコントラクトを作成しています。

[GitHub - ensdomains/ens-contracts](https://github.com/ensdomains/ens-contracts/tree/feature/subdomain-registrar/contracts/subdomainregistrar)

これらのコントラクトには、2つの異なる実装が含まれています。

永久サブネームレジストラ
これは、基本的なFIFS（先着順）レジストラです。登録には固定料金を設定することもできますし、サブネームを無料にしたい場合は0に設定することもできます。名前は自動的に親の有効期限に設定され、登録時にCAN_EXTEND_EXPIRYフューズが燃やされるため、ユーザーは親の有効期限を延長する場合に自分の有効期限を延長できます。より良いユーザーエクスペリエンスのためには、親の有効期限を可能な限り高く設定し、ユーザーが更新を考えなくても済むようにすることをお勧めします。

レンタルサブネームレジストラ
これは、基本的なFIFS（先着順）レジストラです。ユーザーは特定の期間サブネームをレンタルできます。料金は、ENS NameWrapperの新しい解放サブネームのエコシステムで将来の「継続課金」ユースケースを容易にするために、ENS Labsの料金標準と一致しています。
（関連リンク）

ユーザーが有効期限が切れた名前を再登録できるようにするため、解放されたネームと、解放されたリゾルバセットフューズを燃やします。

どちらのコントラクトも次の設定を行います。

.eth 2LDと同じTTLを設定します。
デフォルトのパブリックリゾルバを設定し、サブネームが登録されるたびに「感知」機能が適切に機能するようにします。
登録関数を支払うための料金の概念を持ち、payableを利用してETHを使用します。
登録機能を制限するために、可変値としてrequire()を使用します。例えば、親が所有していない場合や、提供されたラベルが空である場合などです。
また、サブネームが重複しないようにすることを忘れないでください。

その他のケース

もちろん、これらのコントラクトをそのまま使用する必要はありません。例えば、次のような使用例も可能です。

特定のサブネームの登録を許可するホワイトリストを使用するホワイトリストレジストラ。
特定の価格でサブネームをオークションにかけるオークションレジストラ。
独自のサブネームレジストラを作成する際に、それが自動的に機能するように設計してください。レジストラのコントラクトが起動したら、ENS Labsが管理する他の主要なインフラストラクチャ（ENS名解決システム、レジストラ、等）と同様に、「完全に自動」であるべきです。人の介入を必要としないようにしてください。

<img width="1726" alt="スクリーンショット 2024-08-24 8 20 11" src="https://github.com/user-attachments/assets/21a28511-963e-4a40-a736-29c5c9af3d47">

**Comment by mashharuki** [comment]
ブランチ issue_15を作ります。

**Comment by mashharuki** [comment]
https://docs.ens.domains/learn/deployments#deployments
↑ sepoliaのName Wrapperコントラクトの情報はここにあるらしい。
    ABIもある。

**Comment by mashharuki** [comment]
https://sepolia.etherscan.io/tx/0x648466b403928bb4e934365f52c868d9e6d55b299ba058b040eb75830c16c946

↑ sepoliaで撮った時の例。 namewrapperコントラクトも一緒に発行される。

**Comment by mashharuki** [comment]
https://sepolia.etherscan.io/token/0x0635513f179d50a207757e05759cbd106d7dfce8#writeContract
↑ writeメソッド群これを呼び出せば良さそう！！

**Comment by mashharuki** [comment]
![2024-08-24_9 46 26](https://github.com/user-attachments/assets/9e3ccbb4-841d-40c6-9e77-e087f12ea411)
https://sepolia.etherscan.io/tx/0x3eca94462a36572357faa7d46a895e044149e04673a9e1bd68e046ecc7e18e21

発行した！！

NameWrapperコントラクトは以下のとおり
https://sepolia.etherscan.io/token/0x0635513f179d50a207757e05759cbd106d7dfce8?a=64721132857028603551114171706217829955145493623503652799816407145253836364339

**Comment by mashharuki** [comment]
https://sepolia.etherscan.io/tx/0x80eabdc4cdba84756f24bca893e442217729f743c8ef50b4e3539f468f5a7810
↑ 試しに画面からSubDomainを発行してみた時のトランザクション！！

`Set Subnode Record` メソッドが呼び出されている。

https://sepolia.etherscan.io/token/0x0635513f179d50a207757e05759cbd106d7dfce8#writeContract#F18
↑ これだ！！

**Comment by mashharuki** [comment]
@yu23ki14 @ikmzkro 
こちらについては先ほど、プルリクを出しましたので確認お願いします。

**Comment by mashharuki** [comment]
プルリクは、 #39 です！！

**Comment by mashharuki** [comment]
代替案として以下の手順を踏む。

1. まず、サブドメインをリレイヤーに対して発行する(リレイヤーが自分自身に対して発行するようにする)。
2. その後、setAddrメソッドを呼び出して コントラクトウォレットをレコードとして紐づける。

**Comment by mashharuki** [comment]
contract.toban.eth の権限をリレイヤーに渡す。
