### ISSUE TITLE
フロントエンド: ボタンの共通コンポーネントをつくる

### ISSUE THREAD

**Issue by yu23ki14** [hackdays-io/toban#164]
以下プロパティを設定できるようなボタンコンポーネントをつくる
- children
- width (full, 数字)
- size (sm, md, lg)
- backgroundColor
- color

https://daisyui.com/components/button/

**Comment by yawn-c111** [comment]
こちら取り掛かっているのですが、TailwindCSSでは動的にclassNameを設定することができないことを思い出しました！
https://zenn.dev/nemunyan/articles/78c9ffe71cd962

今回のイシューに関して言えば、backgroundColor と color では、オブジェクトで事前にマッピングを定義しておいたうえで引数を元に値を取得するしかなく、また width （数字）では事前定義が難しいため className ではなく style に設定せざるを得ないようです。

そう考えると、DaisyUIやTailwindの良さが失われてしまうかもと思ました。
一番表層のコンポーネントからclassNameをベースコンポーネントまで引き継いで反映させるのが一番かなと考えたのですが、こちら相談させてください。
