### ISSUE TITLE
docs: 実装するコントラクトおよび関数の整理

### ISSUE THREAD

**Issue by ikmzkro** [hackdays-io/toban#17]
## 全体像
<img width="749" alt="スクリーンショット 2024-08-22 20 02 10" src="https://github.com/user-attachments/assets/cc114b85-8704-41bf-95f0-cedc72a43d79">

## 実装するコントラクトおよび関数
※基本的に2771を継承する

ERC2771とMulticallの組み合わせは脆弱性が指摘されているので注意して実装する必要があるかもです。
https://zenn.dev/pokena/articles/95f3cb4e7ba212

### 1. **MultiClaimsFractionHatter.sol**
| 関数名                        | 機能概要                                        | 用途                                              | 引数                                                                                         | 出力                    | イベント                      |
|-------------------------------|------------------------------------------------|---------------------------------------------------|----------------------------------------------------------------------------------------------|-------------------------|-------------------------------|
| `mintHatAndFractionToken`      | HatとFractionTokenを同時にミントする            | ※1         | `address to`, `uint256 hatId`, `uint256 tokenAmount`                                         | `address newTokenAddress`| `HatMinted`, `FractionMinted` |
| `createSplitter`               | SplitterMakerFactoryに依頼してSplitsを作成する |        ※2      | `address[] wearers`, `uint256[] shares`, `address fractionTokenAddress`, `uint256 hatId`     | `address splitterAddress`| `SplitterCreated`             |

※1: プロジェクトごとに新しいHatとトークンを作成
※2: トークン保有者に基づいた分配を行う       

### 2. **Hats.sol**
| 関数名               | 機能概要                                            | 用途                                      | 引数                                             | 出力                      | イベント                    |
|----------------------|----------------------------------------------------|-------------------------------------------|--------------------------------------------------|---------------------------|-----------------------------|
| `mintHat`            | 新しいHatを作成する                                  | 特定の役割やプロジェクトに対して新しいHatを作成  | `address to`, `uint256 hatId`, `address admin`   | `uint256 newHatId`          | `HatMinted`                 |
| `transferHat`        | Hatの所有権を移転する(MultiClaimsFractionHatterにMint権限を付与)                                | Hatの管理者を変更する                       | `address from`, `address to`, `uint256 hatId`    | なし                        | `HatTransferred`            |

### 3. **FractionTokenFactory.sol**
| 関数名                  | 機能概要                                          | 用途                                      | 引数                                              | 出力                       | イベント                     |
|-------------------------|--------------------------------------------------|-------------------------------------------|---------------------------------------------------|----------------------------|------------------------------|
| `createFractionToken`    | 新しいFractionTokenを作成する                    | 新しいプロジェクトや役割に応じたトークン作成  | `address owner`, `uint256 initialSupply`          | `address newTokenAddress`   | `FractionTokenCreated`        |
| `getFractionTokenAddress`| FractionTokenのアドレスを取得する                | 既存のFractionTokenを参照するため            | `uint256 tokenId`                                 | `address tokenAddress`      | なし                         |

### 4. **FractionToken.sol**
| 関数名               | 機能概要                                            | 用途                                              | 引数                                                | 出力                      | イベント                  |
|----------------------|----------------------------------------------------|---------------------------------------------------|-----------------------------------------------------|---------------------------|---------------------------|
| `mint`               | 新しいトークンを指定したアドレスに発行する            | 特定のユーザーに対してトークンをミントする         | `address to`, `uint256 amount`                       | なし                       | `TransferSingle`          |
| `burn`               | 指定されたトークンを焼却する                         | 不要になったトークンを焼却する                      | `address from`, `uint256 amount`                     | なし                       | `TransferSingle`          |
| `balanceOf`          | 指定アドレスのトークン残高を返す                     | ユーザーのトークン残高を確認する                   | `address account`                                    | `uint256 balance`          | なし                      |

### 5. **SplitCreatorContract.sol**
| 関数名                  | 機能概要                                          | 用途                                           | 引数                                              | 出力                       | イベント                     |
|-------------------------|--------------------------------------------------|------------------------------------------------|---------------------------------------------------|----------------------------|------------------------------|
| `createSplitter`         | 新しいSplitterコントラクトを作成する              | トークンの保有者に基づいて報酬を分配する        | `address[] payees`, `uint256[] shares`            | `address splitterAddress`   | `SplitterCreated`            |
| `getSplitterAddress`     | Splitterコントラクトのアドレスを取得する          | 既存のSplitterを参照する                       | `uint256 splitterId`                               | `address splitterAddress`   | なし                         |

**Comment by yu23ki14** [comment]
BigBangトランザクション: プロジェクト作成時に実行するひとつもしくは複数のトランザクションのこと

MultiClaimsFractionHatter.sol
- このコントラクトはプロジェクトごと(Hat Id)に存在し、BigBangトランザクションでFactoryから作成される
- createSplitter関数はSplitCreatorContract.solに入ってるのでなし

Hats.sol（HatProtocolの範疇ですが一旦コメント書いてます）
- transferHatは必要ない？MultiClaimsFractionHatterにそのままHatterHatをMintするので大丈夫かなと思いました

FractionTokenFactory.sol
- FractionTokenのコントラクトはプロジェクトごとでなく１つでいいかも？ERC1155のトークンIDを HatId + address の文字列結合のハッシュ値にする。なのでFactoryコントラクトは作らないパターンでもよさそう。

FractionToken.sol
- mintはMultiClaimsFractionHatter.solと当該HatIdのRootHatのオーナーのみができる制限をかけるのがよさそう。
- burnは所有者のみ
- transferができるように

SplitCreatorContract.sol
- このコントラクトはSplitCreatorFactory.solからHatIdごとに決定論アドレスで作成されるようにする。そうすることで、フロントエンドでプロジェクトで作成したSplits一覧を、Splitsが提供するSDKのgetRelatedSplits関数をつかってバックエンドなしで取得できる。https://docs.splits.org/sdk/data#getrelatedsplits

**Comment by ikmzkro** [comment]
解像度追いついたのでクローズします！
