### ISSUE TITLE
Hats: 貢献分割用のFractionTokenを発行できるように

### ISSUE THREAD

**Issue by yu23ki14** [hackdays-io/toban#3]
役割を持っている人が手伝ってくれた人に対してトークンを分割して渡すことができるようにする。Spritsを作るときにはこのトークンを参照してその保有量を考慮に入れて分配率を決められるようにする。

- [x] FractionTokenFactory.solの実装
- [x] FractionToken.solの実装
- [x] MultiClaimsFractionHatter.solの実装
- [x] 2771対応

## ダイアグラム

![image](https://github.com/user-attachments/assets/0b616b36-73d5-4cf2-b1fb-c96cb1b6d213)

1. MultiClaimsFractionHatterにclaimトランザクションを投げる
2. HatをMintする
3. HatIdとアドレスをキーにして新しいERC1155のトークンをつくり、Hat Wearerに10k発行する

※ MultiClaimsFractionHatter.solは該当HatのAdmin権限を持っている必要がある。

**Comment by ikmzkro** [comment]
フラクションは残り動作確認のみ
