### ISSUE TITLE
Contract: HatsTimeFrameModuleをReactivateとDeactivateに対応

### ISSUE THREAD

**Issue by yu23ki14** [hackdays-io/toban#41]
ReactivateとDeactivate
https://docs.hatsprotocol.xyz/using-hats/deactivating-and-reactivating-hats

個人的な問題や本業が忙しくなったというような場合、一時休止したい場合がある。その分の貢献時間を分配率計算から除くために、ReactivateとDeactivateをTimeFrameHatModuleからできるようにする。

Deactivateした時点からReactivateした時点を引いて、貢献した時間を出せるようにする。

**Comment by ikmzkro** [comment]
チケミーみたいな切り替えが必要。
https://prtimes.jp/main/html/rd/p/000000043.000103622.html

> 本特許では、特定のNFTチケットの「転送許可」の状態と、「転送不許可」の状態を切り替えるための技術が新たな発明として認定されました。

**Comment by yu23ki14** [comment]
getWearingElapsedTime関数を叩いたときに、従事期間が返ってくるようにする

![image](https://github.com/user-attachments/assets/3c443df1-2052-4d22-a342-72b3a10b4f2e)
