### ISSUE TITLE
Frontend & Contract Base: 新規プロジェクト作成ロジック

### ISSUE THREAD

**Issue by yu23ki14** [hackdays-io/toban#5]
HatProtocol上に新しくTreeをつくる（新規プロジェクト作成）
各役割のHatをMintするときにFractionTokenをつくらないといけないので、基本的にはHatterModule経由でMintする必要がある。そのため、Treeの構造はAdmin直下にHatter Hatがはいることになる。

- [ ] Root Hatを作成
- [ ] Hatter Hatを作成 (これがないと各役割ごとのHatをHatterModule.solがミントできないので必要)
- [ ] Hatter Hat をMultiClaimsFractionHatter.solに対してミント

- [ ] SplitterMakerFactoryコントラクトを叩いてプロジェクトのSplitsMakerコントラクトをつくる

![image](https://github.com/user-attachments/assets/dc4fdb86-8c6e-4fdf-9c26-00e9921ba796)

**Comment by mashharuki** [comment]
モノレポ + hardhat

**Comment by ikmzkro** [comment]
- [新しいツリーを作成する](https://zenn.dev/mashharuki/articles/4fc8bb038497aa#1.-%E6%96%B0%E3%81%97%E3%81%84%E3%83%84%E3%83%AA%E3%83%BC%E3%82%92%E4%BD%9C%E6%88%90%E3%81%99%E3%82%8B)
- Mint Top Hat
  - https://sepolia.etherscan.io/tx/0xd9b64b3f51f58cb8c0d13878e3626e929b4a8bae9eb0c77154deea0d18f2a7bc 
  - https://app.hatsprotocol.xyz/trees/11155111/463?hatId=463

**Comment by mashharuki** [comment]
こちらのイシューはもう解決ですよね！

**Comment by mashharuki** [comment]
このクローズはもう完了ですかね？？

**Comment by ikmzkro** [comment]
本当はRootHat作成、HatterMofleまでやりたいが、フロントから単体でやれば実現できる。
TimeFrameのHatterModuleを作成する方向にする
