### ISSUE TITLE
Frontend: プロジェクトトップページ

### ISSUE THREAD

**Issue by yu23ki14** [hackdays-io/toban#6]
プロジェクトごとのトップページのフロントエンド実装

## Wallet未接続
- [ ] プロジェクト名（Hat Treeの名前）
- [ ] プロジェクト情報としてメンバーの数（メンバー一覧への導線）
- [ ] SplitterContractの数（Spritter一覧への導線）
- [ ] Role一覧（各Roleページへの導線）
- [ ] Role新規作成ページへの導線

## Wallet接続積み
Wallet未接続に加えて以下
- [ ] 自分が持っているHatのリスト（個人のRoleページへの導線）

![image](https://github.com/user-attachments/assets/b9449cb3-d57f-48f0-aa09-0b9ce08c8c9a)

**Comment by nfttakerun** [comment]
frontend/app/ProjectTop/page.tsxに作成しました。

**Comment by nfttakerun** [comment]
frontend/app/ProjectTop/page.tsxに作成しました。
