### ISSUE TITLE
作成済みのSplitsを一覧表示するための、Hooksをつくる。

### ISSUE THREAD

**Issue by yu23ki14** [hackdays-io/toban#66]
プロジェクトのSplitter一覧を表示したい。

以下のSDKの関数を使えば、特定のアドレスに関連するSplitterを取得することができる。
なので、これを叩いてリストを返すhooksをつくってほしい。
https://docs.splits.org/sdk/data#getrelatedsplits

テストでは以下のアドレスのrelatedをとったらいけるかなと（Baseだったらデータありそう、はるきさんのアドレスでsplitsつくってもらってもいいです。）
0xdCb93093424447bF4FE9Df869750950922F1E30B

デモではSplitCreatorContractが作成者になるので、relatedはそのアドレスで取ろうと思います。

**Comment by mashharuki** [comment]
splitsのSDKを呼び出すだけのやつを作ると良いかも

**Comment by mashharuki** [comment]
対応します！！
