### ISSUE TITLE
Hats: 役割 x 個人ごとにTimeframeを管理するためのコントラクトに書き込むHatModuleを開発

### ISSUE THREAD

**Issue by yu23ki14** [hackdays-io/toban#7]
Split作成時にどれだけの期間その役割に従事してきたかを考慮できるようにしたい。実現したいことはより長くHatをかぶっている人がたくさんシェアを持てるようになること。

- [x] Timeframe.solの実装
- [x] Timeframe.solのsetWearedTimeをMint時に実行するHatterモジュールの実装

## Timeframe.solが持つべき関数（仮）
Write
- [x] setWoreTime: あるアドレスが、特定のHatをMintされたときのBlocktimestampを保存する関数

Read
- [x] getWoreTime: あるアドレスが、特定のHatをMintされたときのBlocktimestampを返す関数
- [x] getWearingElapsedTime: Mintされた時点から現在までの経過秒数

![image](https://github.com/user-attachments/assets/a758950a-418c-4618-8204-01d516821042)

**Comment by mashharuki** [comment]
ガスレスのために ERC2771を継承してコントラクト開発して欲しいです！

**Comment by ikmzkro** [comment]
夕方、夜までにできていればOK

**Comment by ikmzkro** [comment]
これでHatterがMintした場合に
hatIdを取得→タイムスケジューラへの登録を行えるようにしたい。

https://docs.hatsprotocol.xyz/hats-integrations/hatter-modules/multi-claims-hatter
