### ISSUE TITLE
【ENS Subdomain】 サブドメインに登録したアドレスがresolveできない件

### ISSUE THREAD

**Issue by mashharuki** [hackdays-io/toban#72]
サブドメインに登録したアドレスがresolveできない件。

ハッカソンで作った状態ではOZ defenderを使ってバックエンドEOAから無理やりsubdomainとspritterコントラクトを紐づけている状態。

これらの名前解決を行うためには直接的な関数が実装されていないので The Graphなどを使う必要あり。

フロントエンドを改修する時には、The Graphの使用を検討する必要あり。

**Comment by yu23ki14** [comment]
op.eth, base.eth

**Comment by mashharuki** [comment]
https://api.studio.thegraph.com/proxy/49574/enssepolia/version/latest/graphql?query=%23%0A%23+Welcome+to+The+GraphiQL%0A%23%0A%23+The+GraphiQL+is+an+in-browser+tool+for+writing%2C+validating%2C+and%0A%23+testing+GraphQL+queries.%0A%23%0A%23+Type+queries+into+this+side+of+the+screen%2C+and+you+will+see+intelligent%0A%23+typeaheads+aware+of+the+current+GraphQL+type+schema+and+live+syntax+and%0A%23+validation+errors+highlighted+within+the+text.%0A%23%0A%23+GraphQL+queries+typically+start+with+a+%22%7B%22+character.+Lines+that+start%0A%23+with+a+%23+are+ignored.%0A%23%0A%23+An+example+GraphQL+query+might+look+like%3A%0A%23%0A%23+++++%7B%0A%23+++++++field%28arg%3A+%22value%22%29+%7B%0A%23+++++++++subField%0A%23+++++++%7D%0A%23+++++%7D%0A%23%0A%23+Keyboard+shortcuts%3A%0A%23%0A%23++Prettify+Query%3A++Shift-Ctrl-P+%28or+press+the+prettify+button+above%29%0A%23%0A%23+++++Merge+Query%3A++Shift-Ctrl-M+%28or+press+the+merge+button+above%29%0A%23%0A%23+++++++Run+Query%3A++Ctrl-Enter+%28or+press+the+play+button+above%29%0A%23%0A%23+++Auto+Complete%3A++Ctrl-Space+%28or+just+start+typing%29%0A%23%0A

↑ sepoliaのENSサブグラフ

**Comment by mashharuki** [comment]
```gql
query MyQuery {
  domains(where: {name: "test.toban.eth"}) {
    name
    expiryDate
    createdAt
    subdomainCount
    ttl
    labelName
    owner {
      id
      wrappedDomains {
        name
      }
    }
    events {
      domain {
        name
        subdomainCount
      }
    }
  }
  newOwners(where: {domain: "toban.eth"}) {
    owner {
      domains {
        labelhash
        name
        labelName
        subdomainCount
      }
    }
  }
}
```

↑ サブグラフで取ってこれるか？？

**Comment by mashharuki** [comment]
検証中

**Comment by mashharuki** [comment]
https://github.com/ensdomains/ens-subgraph/blob/master/schema.graphql
↑ スキーマはここで確認できる。

https://docs.ens.domains/web/subgraph
↑ こんな風に取って来れたら最高

**Comment by mashharuki** [comment]
<img width="830" alt="スクリーンショット 2024-09-01 23 40 31" src="https://github.com/user-attachments/assets/d1f164dc-91ec-46ca-887d-c681fb779557">

**Comment by mashharuki** [comment]
https://docs.ens.domains/web/subgraph#searching-for-a-subdomain

↑ subdomain探すサンプルクエリあった！！

**Comment by mashharuki** [comment]
<img width="1668" alt="スクリーンショット 2024-09-01 23 43 29" src="https://github.com/user-attachments/assets/9d373d6f-81ce-43fa-8a4e-1a7b9fe73ecc">

↑ 取って来れた！！！

```gql
query getSubDomains($Account: String = "toban.eth") {
  domains(where: { name: "toban.eth" }) {
    name
    id
    subdomains(first: 10) {
      name
    }
    subdomainCount
  }
}
```

↑ 試したクエリ

**Comment by mashharuki** [comment]
```gql
query getSubDomains($Account: String = "contract.toban.eth") {
  domains(where: { name: "contract.toban.eth" }) {
    name
    id
    subdomains(first: 10) {
      name
      owner {
        id
      }
    }
    subdomainCount
  }
}
```

↑ これでも引っ張って来れる！！

**Comment by mashharuki** [comment]
<img width="772" alt="スクリーンショット 2024-09-01 23 47 54" src="https://github.com/user-attachments/assets/eb9d6211-09c2-47f8-bd91-02885
<img width="1728" alt="スクリーンショット 2024-09-01 23 48 06" src="https://github.com/user-attachments/assets/111566e4-8522-4de2-86bd-a1dc06cd2f43">
05518a4">

↑ きたかも！！！

```gql
query getSubDomains($Account: String = "contract.toban.eth") {
  domains(where: { name: "contract.toban.eth" }) {
    id
    name
    subdomainCount
    subdomains(first: 10) {
      name
      owner {
        id
      }
      resolvedAddress{
        id
      }
    }
  }
}
```

**Comment by mashharuki** [comment]
```gql
# 特定のアドレスと紐づくサブドメインを取得するサブクエリ
query getSubDomains($Account: String = "contract.toban.eth") {
  domains(where: { 
    name: "contract.toban.eth" 
  }) {
    subdomains(where: { 
      resolvedAddress: "0x06edd105b205eae5d6a2d319c2605f4c632073e4" 
    }) {
      name
    }
  }
}
```

**Comment by mashharuki** [comment]
https://github.com/mashharuki/ENS-TheGraph-Sample

↑ 検証用にリポジトリを作成
