### ISSUE TITLE
Frontend: 個人のRoleページ

### ISSUE THREAD

**Issue by yu23ki14** [hackdays-io/toban#8]
自分が持っているロールの情報閲覧ページ
**ロール閲覧ページとは違うので注意**

**FractionTokenシェアへの導線は必須**

- [ ] ロールの基本情報（画像、名前、開始時間 timeframe_modules、説明、ワークスコープと責任）
- [ ] 自分のFractionalTokenをシェアした人たちのリスト、シェアの円グラフ
- [ ] Renounceのボタン

![image](https://github.com/user-attachments/assets/b20c6b37-c7ba-4f79-8ef5-b33007973792)

**Comment by nfttakerun** [comment]
frontend/app/IndividualRoleList.tsxに作成しました

**Comment by nfttakerun** [comment]
frontend/app/IndividualRoleList.tsxに作成しました
